my_name = "Priscilla Abena Aboagye"
my_age = 12
my_age_changed = "12"
print(my_name.isalpha())
print(my_age_changed.isalnum())
print(my_name.startswith("P"))
print(my_name.startswith("A"))
print(my_name.startswith("p"), "\n")
print(my_name.find("s"))
print(my_name.find("a"))
print(my_name.find("A"), "\n")
print(my_name.count("A"))
print(my_name.count("B"))
print(my_name.count("e"))
print(my_age_changed.count("1"))
print(my_name.replace("a", "b"))
print(my_age_changed.replace("1", "5"))
print(my_age_changed.split())
print(my_name.split())
print(my_name.strip("e"))
print(my_name.strip())
print(my_name.strip("P"))
print(my_name.upper())
print(my_name.lower())